### ISSUE TITLE
Ignored swatches cause error 

### ISSUE THREAD

**Issue by sydney-d** [marijnvdwerf/material-palette-php#14]
Hello,

With some images I get this error : 
```error
max(): Array must contain at least one element
Palette.php","line":81,"function":"max"
```

I tracked the error down and it's caused by the `shouldIgnoreSwatch` function, and more precisely to `isNearRedILine`.

I don't understand the meaning of `isNearRedILine` but it's causing the swatches array to be empty.
Would be nice if we could customize `shouldIgnoreSwatch` as proposed here : https://github.com/marijnvdwerf/material-palette-php/issues/12
Or at least if Palette.php could handle an empty array without throwing an error.

Example image: 
![image](https://user-images.githubusercontent.com/46789893/132982973-2849b0a3-02c4-4dcb-b65f-e6d32b1550a4.png)

Surely I can work on a PR if you explain the meaning of _isNearRedILine_

Thanks

**Comment by marijnvdwerf** [comment]
I actually have no idea what the 'isNearRedILine' stuff meant either. I basically translated this from Java to PHP, trying to keep all behavior the same. The original library has changed quite a bit by now, but the redIline stuff is still in there. https://github.com/aosp-mirror/platform_frameworks_support/blob/master/palette/src/main/java/androidx/palette/graphics/Palette.java#L986

**Comment by sydney-d** [comment]
Hello,

I contacted one of the google devs in charge of this project and he explained that the purpose of that filter is to try and omit skin tones from the return swatches.

I definitely want skin tones in my swatches so I think I'll work on a fork.

Best

**Comment by marijnvdwerf** [comment]
Thanks for asking the google devs! FYI, I wouldn't mind the project getting updated to match the newer API, but since I'm not using it myself at this point, I don't want to put too much effort in it.
