### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bradbonkoski** [marijnvdwerf/material-palette-php#3]
Could you please define a License for this so I can figure out if I am able to use it?

**Comment by on2** [comment]
@marijnvdwerf, are you still maintaining this library? I'd like to address some of the issues, especially #8, but I could do with your input on a license first.

**Comment by marijnvdwerf** [comment]
I haven't had a real need for this library myself anymore, so I stopped working on it. I might have some local branches though, so I might push those.

I ported the [original Java-based Palette library](https://github.com/aosp-mirror/platform_frameworks_support/tree/androidx-master-dev/palette/palette) which is under the Apache license. Would you be okay with it being under that license as well? I'm personally not that invested in software licenses.

**Comment by on2** [comment]
Your library seems to do everything we want to do with it as it is, so thanks for porting it. I'm interested in fixing some of the bugs that others have noted as they affected us too and I don't think there's anything else out there for PHP that does something similar.

The Apache license would be fine with us. I did try and find the original source as I thought that you may be forced to use the same license but I couldn't find it.

Expect a pull request from me soon!
