### ISSUE TITLE
asHSLColor() not working as expected

### ISSUE THREAD

**Issue by nicolas-t** [marijnvdwerf/material-palette-php#5]
Hello ! 

thanks for this library, i've tried a lot of color extraction php libs and this one is by far the best.

But there's a problem when converting a color to HSL the hue value seems wrong.

``` php
$color = new \marijnvdwerf\palette\Color\RGBColor(0.8, 0.5, 0.2)

(string) $color
// => "rgb(204, 128, 51)"
// this is right

(string) $color->asHSLColor()
// => "hsl(0.000000, 60.000000%, 50.000000%)"
// this is wrong

(string) $color->asHSLColor()->asRGBColor()
// => "rgb(204, 51, 51)"
// this is different from the color we entered in the constructor
```

Best regards,

**Comment by marijnvdwerf** [comment]
Thanks for the report and sorry for the late reply. I managed to fix the bug, and started adding tests because of it :)
